### PR TITLE
Port for Fabric 1.19

### PR DESCRIPTION
**Pull request by IzzyBizzy45**
Let me know if you want anything changed specifically, Just made enough changes to get it working on Fabric 1.19 without loosing any functionality. Bumped version to 2.9.2 from 2.9.1 as it's technically an update.

### CODE REVIEW

**Comment by pupnewfster** [comment]
I don't do any fabric modding but instead of `Text.literal("")` isn't there a `Text.empty()` that would be of better use in those spots?

**Comment by IzzyBizzy45** [comment]
> I don't do any fabric modding but instead of `Text.literal("")` isn't there a `Text.empty()` that would be of better use in those spots?

Fair point, I was more concerned with just moving the older functions to be the new ones. Updated it, will test with the github actions for you Kichura

**Comment by IzzyBizzy45** [comment]
18ish hours later and github actions still doesn't have a runner for the job. Testing with a manual build on a normal fabric client has it working without any issues, so if github finds a runner it should validate fine

**Comment by PhoenixAceVFX** [comment]
i was able to get a runner for the workflow right as i pushed a commit which in turn made 2 workflows happen. not sure whats going on with your repo but i think you might need to cancel the queued one and try again.

**Comment by IzzyBizzy45** [comment]
I'm not sure what's happening with mine. Even re-creating the file just leaves it still trying to find a runner. As it runs on PhoenixAceVFX's fine, I presume it should work fine if this gets merged (you can ignore the last two commits. Just confused why my one is being weird.

**Comment by PhoenixAceVFX** [comment]
yea you can grab it from my fork if needed, i only made the fork to test the runner

**Review by Kichura — COMMENTED** [review]
Should be "Build fabric mod with Gradle" if i had to be honest.

**Comment by Kichura** [comment]
Forgot something since i looked into the PR, the workflow should be named "fabric.yml" and it says "buildfabric" instead, is that a typo?

**Comment by IzzyBizzy45** [comment]
Sorta, it was another rename to try get actions to work with the intention to change it back incase something else needed to be updated before the PR was completed. Actions still reads it fine and is _trying_ to build it. Did you want me to change it back to "fabric.yml"?

**Comment by Kichura** [comment]
> Sorta, it was another rename to try get actions to work with the intention to change it back incase something else needed to be updated before the PR was completed. Actions still reads it fine and is _trying_ to build it. Did you want me to change it back to "fabric.yml"?

Would be the best to try and not end up making it look like a typo.

**Review by Kichura — APPROVED** [review]
Looks good now.

**Pull request merged**
