### PR TITLE
Port to 1.19.3 [Fabric]

### LINKED ISSUE #88: Error on version 1.19.3, while starting the game
After updating to version 1.19.3, it started giving an error. Perhaps this is due to changing the positions/names of the necessary classes. The same vec3f changed the position of the class and its variables.

> Minecraft: 1.19.3
> Fabric: 0.14.11
> Fabric API: 0.68.1
```log
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-12-12 20:48:43
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'wildfire_gender'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
Caused by: java.lang.NoSuchMethodError: 'void net.minecraft.class_3414.<init>(net.minecraft.class_2960)'
	at com.wildfire.main.WildfireSounds.<clinit>(WildfireSounds.java:27)
	at com.wildfire.main.WildfireGender.onInitializeClient(WildfireGender.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:465)
```

### PR DESCRIPTION
**Pull request by celestialfault**
Largely a wholesale port to 1.19.3, but also includes some small miscellaneous code style changes.

Fixes #88

### CODE REVIEW

**Comment by Slooshie1** [comment]
Prism Launcher goes unresponsive when I click edit instance when this mod is in my mods folder

**Comment by Kichura** [comment]
> Prism Launcher goes unresponsive when I click edit instance when this mod is in my mods folder

Launcher bug and not the mod itself.

**Comment by diademiemi** [comment]
Works fine with Prism Launcher for me, though that wouldn't have been an issue on from this mod even if it didn't.

This PRs branch works for me, thanks! Hope it gets merged

**Comment by WildfireRomeo** [comment]
Updated it myself, thanks for the PR though!

**Pull request closed without merging**
