### PR TITLE
Port to 1.19, and make use of parchment for mapping parameter names

### PR DESCRIPTION
**Pull request by pupnewfster**
I recommend creating a new branch for 1.19 and retargetting this PR to that branch before merging.

### CODE REVIEW

**Review by Kichura — COMMENTED** [review]
Looks good although credited people should be re-sorted in alphabet order + version itself should be increased by 1 or something iirc.

**Comment by pupnewfster** [comment]
Sorted the credits even though it seems kind of pointless to me. Also I didn't bump the version as I am unsure what wildfire wants it at.

**Comment by Kichura** [comment]
> Sorted the credits even though it seems kind of pointless to me. Also I didn't bump the version as I am unsure what wildfire wants it at.

thanks, will go ahead and close my own pr.

**Comment by Kichura** [comment]
I pushed out a pull request to your own one since github workflow needs to be updated.

**Review by Kichura — APPROVED** [review]
Looks good to go, well done.

**Pull request merged**
