### PR TITLE
Rewrite how configuration data is stored/accessed

### PR DESCRIPTION
**Pull request by celestialfault**
This is a *very* large and substantial rewrite to how configurations are handled internally, aiming to make using & adding to them significantly less tedious.

These changes also have the side-effect of largely removing most (if not all) regular config map lookups, which may slightly improve performance (although likely by a fairly negligible amount at most).

Do note that this PR has not seen very extensive testing, especially with regards to the UI changes required.

This is also a draft because - despite this having seen *some* testing - there hasn't been nearly as much testing done on this as I'd like for how substantial these changes are.

### CODE REVIEW

**Comment by WildfireRomeo** [comment]
That's an extensive PR O.O

I will say though, I didn't find it that difficult to add new config keys, personally.

**Comment by celestialfault** [comment]
> I will say though, I didn't find it that difficult to add new config keys, personally.

Not exactly *difficult*, but instead *more inconvenient* than I personally would like it to be - adding new player config options specifically requiring adding a `.setDefault(ConfigKey)`, `.get(ConfigKey)`, and `.set(ConfigKey, TYPE)` in `PlayerConfig` is definitely a *lot* compared to the single `register(ConfigKey)` call required when constructing a config class with these changes.

**Comment by WildfireRomeo** [comment]
Fair enough, I just get scared when I see half-mod rewriting changes haha

**Comment by celestialfault** [comment]
that's entirely fair, lol - I didn't think this would end up being such a massive diff, but uh, oops! turns out everything uses the config so everything had to change to adapt to it

**Comment by WildfireRomeo** [comment]
I'm really debating whether or not I like this change lol.

I know pupnewfster made a PR a few years ago with a Configuration change as well, and I never merged it because it changed how the mod worked too much for my taste.

It's difficult for me to want to merge this too. I like the old way it's set-up a lot more personally, even if it is a little more inconvenient to add new configurations.

I just don't wanna drop all the work you put into this PR, because I'm sure this took hours...

**Comment by celestialfault** [comment]
> I know pupnewfster made a PR a few years ago with a Configuration change as well, and I never merged it because it changed how the mod worked too much for my taste.

very understandable - that pr was partly what made me look into this, but i can definitely see why you'd say that now

> [...] even if it is a little more inconvenient to add new configurations.

i might come back to this specific issue at some other point to try to improve this (probably by just moving the `PlayerConfig` config-related methods into `Configuration` so they're all in one place), but this is *probably* a bit much now that i think about it

> I just don't wanna drop all the work you put into this PR, because I'm sure this took hours...

¯\\_(ツ)\_/¯ oh well

**Pull request closed without merging**
