### PR TITLE
Update workflow, 1.21.1 (NeoForge) #2

### PR DESCRIPTION
**Pull request by Kichura**
Same as last PR, also a little lesson: don't change base branch to the other as that one re-uses same code from fabric-1.21.3.

### CODE REVIEW

**Comment by WildfireRomeo** [comment]
Did I copy the wrong branch when I did it?

**Comment by Kichura** [comment]
> Did I copy the wrong branch when I did it?

You copied `fabric-1.21.3` as the template instead of `neoforge-1.21` lol.

**Comment by WildfireRomeo** [comment]
THAT'S WHY IT BROKE. I was wondering cuz I've been doing the copy thing for a while now.

**Comment by WildfireRomeo** [comment]
LET'S TRY THIS AGAIN

**Pull request merged**
