### PR TITLE
Update to 1.20.4

### PR DESCRIPTION
**Pull request by RacoonDog**
Update to 1.20.4
- updated loom/gradle wrapper to fix crash with MixinExtras
- migrated annotations from javax to jetbrains due to gradle wrapper update dropping the javax transitive dependency
- replaced fabric api dependency with individual modules to lower classpath size in development

support for 1.20.3 is maintained

### CODE REVIEW

**Comment by RacoonDog** [comment]
closes #171

**Comment by sternschnaube** [comment]
Thanks for the update!!

**Comment by snwyyylol** [comment]
how do i download  this

**Comment by Poqqerss** [comment]
> how do i download this

did you figure it out

**Pull request merged**
